### ISSUE TITLE
block clone and block copy + paste not working

### ISSUE THREAD

**Issue by hcv242** [kmatheussen/radium#745]
block clone and block copy + paste not working in 4.2.6
i dont know if it worked before. this is the first time im trying to use this feature.

regards

**Comment by kmatheussen** [comment]
What exactly are you doing? Everything works fine as far as I can see, but
the block clone feature was implemented in 4.2.6, so I guess some things
are likely not to work.

**Comment by kmatheussen** [comment]
Maybe there's a misunderstanding. If you selected "Paste block"
from the menus, this function does not paste into the sequencer.
"Paste block" pastes the last copied block into the current block.
I don't think anything in the menues are related to the sequencer.
The sequencer is a very new feature, currently under development.

If you want to insert a new block into the sequencer, you need
to right click where to insert, and then select insert current/existing/new.



On Mon, Nov 14, 2016 at 9:24 AM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> What exactly are you doing? Everything works fine as far as I can see, but
> the block clone feature was implemented in 4.2.6, so I guess some things
> are likely not to work.
>

**Comment by onukore** [comment]
hi !
that work for me ..

**Comment by hcv242** [comment]
block clone is working. i was expecting a different result.
but i cant understand copy block + paste.
ive made a video. in the video i try to copy block 0 to block 1. tell me what i am doing wrong, please.
ive used trackers for a long time, radium leaves me clueless, though :)

https://www.youtube.com/watch?v=0UhL1Xh6Wz4

and another issue also in the video: when i click open song, the open\browse window takes a long time to pop up. this computer is an i7 and i only have two omnisphere vstis loaded. no other app takes this time to show me an open menu.

**Comment by kmatheussen** [comment]
That's definitely a bug. Thank you for reporting.
But it's just a bug in the menus. You can
use the short cuts "Left Ctrl + C" / "Left Ctrl + V" to copy
and paste instead.

**Comment by kmatheussen** [comment]
I don't know why the file requester takes so long time to open.
I haven't seen it before, but I'll look at it.


On Mon, Nov 14, 2016 at 5:38 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> That's definitely a bug. Thank you for reporting.
> But it's just a bug in the menus. You can
> use the short cuts "Left Ctrl + C" / "Left Ctrl + V" to copy
> and paste instead.
>
>
>

**Comment by Lykdraft** [comment]
Also when you want to "clone" a block, you probably want to go  CTRL-I first, to create a new empty block to paste into.

**Comment by kmatheussen** [comment]
I think he talks about the new "Clone block" option when you right click
on a block in the sequencer.

**Comment by kmatheussen** [comment]
Or maybe not. That's probably something I imagined.

On Mon, Nov 14, 2016 at 5:45 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by Lykdraft** [comment]
I think here are two threads right now with similar issues... Maybe that's why? :)

Anyways, chained keycomand to do a "clone" block" before "Clone block" was actually added to the seqemncer menu:
L_CTRL_C 
L_CTRL_I
LCTRL_F
L_CTRL_V

(with CTRL_F and CTRL_A to move to next/prior block)

**Comment by hcv242** [comment]
yes, i was talking about the new clone block option with right click. i expected another block to be added in front of the one i had right clicked.
a sugestion: could there be an option to avoid the pattern to scroll up and down if it fits the window? if i can see 64 lines at once (wich is the size of my pattern) why should it scroll ?

**Comment by kmatheussen** [comment]
Hi, there is a button "FC" in the bottom bar you can press
to stop scrolling when playing.

**Comment by kmatheussen** [comment]
Sorry, "PC" (play cursor), not "FC".

On Mon, Nov 14, 2016 at 8:39 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> Hi, there is a button "FC" in the bottom bar you can press
> to stop scrolling when playing.
>
>

**Comment by Lykdraft** [comment]
The word: "Clone Block" is a bit confusing I think.

I think what you (hcv242) and Onukore meant in the first place isn't really "Clone Block",
but insert the same block on the sequencer timeline again to build up a quick arrangement of the same block. Correct? (Alias or Ghost copy in usual DAW Terms...)

Clone Block actually does what is says, namely make a duplicate/clone of the current one.

**Comment by onukore** [comment]
no for me clone block is create a new block with old one, that work very fine for me , i have no problem when a clone block radium create a same new block, with a oher name, and a don't have problem with load song pop with my two pc (desktop and laptop core i7) all work fine , juste copy and paste block in menu, i use always shortcut it's because i don't see the bug..

**Comment by Lykdraft** [comment]
@onukore 👍

**Comment by onukore** [comment]
;)

**Comment by kmatheussen** [comment]
Can you check if the file requester is still slow in the latest version?
I've added a flag so that it doesn't search for custom directory icons,
which according to the Qt documentation may increase startup time.
I don't see anything else that could cause longer startup time.

**Comment by hcv242** [comment]
your latest build didnt fix it. also its not only the file requester window that is slow, its radium video performance in general. ive tried 32 and 64 bits and ive also tried playing with the video settings in radium. no luck. ive noticed something else. after radium is loaded, chrome also gets incledible slow video performance wise. this doesnt seem to affect other apps like renoise, though.

i have tried to make a song so i could test this better. my first impressions:

ive loaded omnisphere wich is a multitimbral vsti in track 0. channel 0 is set to midi channel 1. ive assigned the same omnisphere instance to track 1 and set it to midi channel 2. when i insert notes with the keyboard on track 1, i hear the preview notes of track 0. the track im on (midi channel 2) is sending midi channel 1.

on a side note, the first track shoud be named track 1 and not track 0. musicians are not machines :)

Does radium supports vsti with multiple audio outputs?

after a block paste, the cursor changes position. this is annoying.

it would be nice to have a shortcut key to open the vsti gui of the channel where the cursor is

shortcut keys to navigate the block sequence up and down like in fasttrack

at my first play with radium i've tried to copy notes by selecting them with the mouse and clicking copy like in other app or even any other tracker, but that action adds notes to the pattern. i really dont like that method. could it be optional to use the mouse for selecting ranges\areas?

if a click adds a note to a pattern i was expecting that a double click would delete it, but it does nothing.

sometimes there are some lines of a track where double clicking to add notes with the mouse doesnt work. this happened twice but i cant reproduce it now.

when i open the preferences menu, it always apears on the right end corner of my screen and a good part of it is out of the screen. i always have to move the window inside the screen.

the play menu shows several play options. there is one called block from top, wich is assigned to to the key "Play". wich pc keyboard key is that? (found that now, its right shift)

page down and page up move the cursor 32 lines. 16 lines, one bar is a lot more useful. can this be configured ?

i miss global swing, like in renoise or abletong live

im on a i7 pc with 8 gb ram running windows 7.

hope this helps.

**Comment by Lykdraft** [comment]
> ive loaded omnisphere wich is a multitimbral vsti in track 0. channel 0 is set to midi channel 1. ive assigned the same omnisphere instance to track 1 and set it to midi channel 2. when i insert notes with the keyboard on track 1, i hear the preview notes of track 0. the track im on (midi channel 2) is sending midi channel 1.

AFAIK this is a known issue. It should be fixed, but maybe it is not? DEV needs to check.... 
Playback should be fine though (Midi notes on playback should playback on the correct channel)

> on a side note, the first track shoud be named track 1 and not track 0. musicians are not machines :)

I **strongly** disagree here... :) Because "remoting" Radium with hotkeys in such a convenient way like you can do now, **requires** to start from zero. At the beginning this might be odd, 
but believe me: this is a **huge** plus once you get used to the (custom) key commands and start to work with track-counts above 10. Renoise doesn't do this and is a hotkey-mess because of that.
And by the way: I really would go **full** retard, if that would change... ;)

_(higher numbers above 10 until even 40+ tracks are sooooo easy to manage with that system...
Just the first 0-9 are "strange" in the beginning...)_

(BTW: I am starting a tutorial series soon on Youtube somewhere mid/end December.
I'll explain stuff like this in detail then and also why I think this is superior numbering... )

> Does radium supports vsti with multiple audio outputs?

It does indeed. It is a bit difficult to explain, and also quite tricky to setup.
I will upload a .rad song tomorrow where you can see how it is done.
Because we now have the ability to save .mrec files (multiple modules as a "grouped" network at once) you just need to save it at a dummy and "replace" my VSTi with the VSTi of your liking.

(I hope .rad files are cross-platform as I am on OSX? But I think they should be?)

See example on how this looks here:
![____users_luetze_music_radium_radium_projects_vps_phalanx_full_setup_one_rad___](https://cloud.githubusercontent.com/assets/18437561/20331444/8b9e7c52-aba5-11e6-9e2d-c3f66911b38d.jpg)



> it  would be nice to have a shortcut key to open the vsti gui of the channel where the cursor is
> shortcut keys to navigate the block sequence up and down like in fasttrack

Both would be nice, absolutely.  You can never have enough key commands.
I also recommended today in an older thread key commands to do next/prev preset
for VSTs. 

> could it be optional to use the mouse for selecting ranges\areas?

Range-select and other Range related FRs are already somewhere on here.
Maybe they are buried in the group, not sure. But I am sure I came up with this as well at some point.
I agree that Range selection is still a bit awkward and slow compared to some other methods,
especially in other trackers. They usually are quite advanced with selecting/editing/shifting and transforming ranges in various ways. But I am sure we will see progress here soon as well.

_Also, you soon will  find that getting comfortable with marking areas per hotkey
(On OSX cmd-B to mark and cmd-z to unmark, not sure about the windows equivalent)  
is an essential part of very fast and fluid workflow in Radium anyways... (Will also be tackled immediately in one of the first tutorials, as this is quite important....)_

Reminder:  I also had a FR somewhere regarding shifting notes up and down inside a marked range in a way that when a note "leaves" the last line of the marked area it "appears" again on the first line of the marked are.. might be best described as some kind of "Modulo" or "Rotate" Function...
and then, of course there still is all this stuff: #509  ;)  .)_ 

But back on topic: I remember that I suggested already to look at the mixer window. We already have the possibility for rectangular selection there, but I reckon that this is a bit more tricky to realize in the track list. 

> page down and page up move the cursor 32 lines. 16 lines, one bar is a lot more useful. can this be configured ?

This is configurable. Albeit I need to look that up myself. Also the process with the keycommand.conf is different on OSX that it is on windows. One of the other guys might be able to help you better with this one.

> i  miss global swing, like in renoise or abletong live

This also is already a pending FR. Also comes up quite often.. ;)
For now, if you can't get your head around sublines/subline swing,
(see an exampleof that technique here: https://vimeo.com/162647680 )
I would highly suggest looking into PIZ Midi Tools, where you also have a midiSwing module, 
that you can use. (http://thepiz.org/plugins/?p=pizmidi )
Probably there is even more free stuff like that for PC.

You can do a lot with midi modules and modifiers anyways... Just remember you have 
**green** midi-connection cables as well... And when you use midi-modifiers (also arpeggiators and things of that nature) that you need to disable that.. See here (Click to enlarge):
![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/20331261/b0a14486-aba4-11e6-8ff4-e970aa9fc0db.jpg)




Best,
tL.

**Comment by kmatheussen** [comment]
> your latest build didnt fix it. also its not only the file requester
> window that is slow, its radium video performance in general. ive tried 32
> and 64 bits and ive also tried playing with the video settings in radium.
> no luck. ive noticed something else. after radium is loaded, chrome also
> gets incledible slow video performance wise. this doesnt seem to affect
> other apps like renoise, though.
>
>
Which gfx card do you have? Maybe it helps to update the driver.



> i have tried to make a song so i could test this better. my first
> impressions:
>
> ive loaded omnisphere wich is a multitimbral vsti in track 0. channel 0 is
> set to midi channel 1. ive assigned the same omnisphere instance to track 1
> and set it to midi channel 2. when i insert notes with the keyboard on
> track 1, i hear the preview notes of track 0. the track im on (midi channel
> 2) is sending midi channel 1.
>
>
Can you explain it again? Also, are "track" and "channel" the same, or does
"track" refer to sequencer
track and "channel" to editor track? It would help if you could describe
the problem like this:

1. Assign Ominsphere vst to track 1.
2. Set track 1 to MIDI channel 2.
...
7. I expected X to happen, but instead Y happened.




> on a side note, the first track shoud be named track 1 and not track 0.
> musicians are not machines :)
>
Does radium supports vsti with multiple audio outputs?
>

Yes. The connection lines you see in the mixer are not mono channels. If you
want to split or combine separate channels you can use one of the
"patchbay" objects.
(if you need to configure more than 32 channels, you can use the FaustDev
object)



> after a block paste, the cursor changes position. this is annoying.
>
> it would be nice to have a shortcut key to open the vsti gui of the
> channel where the cursor is
>
> shortcut keys to navigate the block sequence up and down like in fasttrack
>
> at my first play with radium i've tried to copy notes by selecting them
> with the mouse and clicking copy like in other app or even any other
> tracker, but that action adds notes to the pattern. i really dont like that
> method. could it be optional to use the mouse for selecting ranges\areas?
>
> That's a bit difficult since the mouse is used for so much things already.
If it's slow to mark a range with the keyboard shortcuts, perhaps we need
better keyboard shortcuts for navigating...



> if a click adds a note to a pattern i was expecting that a double click
> would delete it, but it does nothing.
>

To delete, use shift + right mouse button. See the "Help" menu.



> sometimes there are some lines of a track where double clicking to add
> notes with the mouse doesnt work. this happened twice but i cant reproduce
> it now.
>

I don't think double clicking is used anywhere in the program except for
opening a plugin gui.



> when i open the preferences menu, it always apears on the right end corner
> of my screen and a good part of it is out of the screen. i always have to
> move the window inside the screen.
>
> the play menu shows several play options. there is one called block from
> top, wich is assigned to to the key "Play". wich pc keyboard key is that?
> (found that now, its right shift)
>
>
There are three shortcuts to play block in the menus. When a line only
contains "." it
means that the line above is repeated. The "PLAY" button is a relatively
common key
on PC keyboards. It's part of the "media keys" along mute, volume up and
volume down.



> page down and page up move the cursor 32 lines. 16 lines, one bar is a lot
> more useful. can this be configured ?
>

Yes, you can edit the bin/keybindings.conf file. But you can also use
right shift + up/down, which will scroll 8 lines.

**Comment by onukore** [comment]
issue #712 for midi channel
the computer keyboard and midi keyboard always send to midi channel 1
if you set midi channel 2 in track header for vsti using multi midi channel, It only receives channel 1 message from the computer keyboard or the midi keyboard

**Comment by hcv242** [comment]
> Which gfx card do you have? Maybe it helps to update the driver.

Nvidia Gforce GT 740M and the i7 built in one, an intel graphics 4000.
since you asked, it reminded me check wich one was radium using.
it was set to use the intel card. ive changed it to the nvidia one and now it opens the window a lot faster.
it's a LOT faster but its still not instant. radium is heavy on graphics i guess.

>Can you explain it again? Also, are "track" and "channel" the same, or does

sorry. i was super sleepy. ive misspelled a word. what i meant was:

 ive loaded omnisphere wich is a multitimbral vsti in track 0. track 0 is
 set to midi channel 1. ive assigned the same omnisphere instance to track 1
 and set it to midi channel 2. when i insert notes with the keyboard on
 track 1, i hear the preview notes of track 0. the track im on (midi channel
 2) is sending midi channel 1.

as onukore mentioned it's issue #712  and its not fixed. at least on pc.

>If it's slow to mark a range with the keyboard shortcuts, perhaps we need
better keyboard shortcuts for navigating...

having only one key to select areas (win+b) it's a bit awkward, because if you want to select another area, you have first to unselect the previous one (win+z). The way renoise deals with this is by having two keys, one for range start and another one for range end. like this, you dont need to unselect your previous range.

>To delete, use shift + right mouse button. See the "Help" menu.

thanks for the tip.
using the mouse plus the keyboard to do one action that could be done with just the mouse doesnt make much sense. as you said double clicking is still free/not used by any option.

>I don't think double clicking is used anywhere in the program except for
opening a plugin gui.

Im sorry again. sleep made me say this. i meant just one click.
rephrasing: sometimes, when i click on the note row, instead of adding a note, a little hand will apear. this only happens sometimes. 

>Yes, you can edit the bin/keybindings.conf

this is great to know :) i've checked the file. it wont be easy though.
but my real questions was : can i set how many lines the keys "page up" and "page down" jumps in the pattern. in renoise, fastracker 2 it jumps 16 lines (one bar).

**Comment by kmatheussen** [comment]
On Wed, Nov 16, 2016 at 8:44 PM, hcv242 <notifications@github.com> wrote:

> Which gfx card do you have? Maybe it helps to update the driver.
>
> Nvidia Gforce GT 740M and the i7 built in one, an intel graphics 4000.
> since you asked, it reminded me check wich one was radium using.
> it was set to use the intel card. ive changed it to the nvidia one and now
> it opens the window a lot faster.
> it's a LOT faster but its still not instant. radium is heavy on graphics i
> guess
>

Perhaps you have disabled vsync under Edit->Preferences->OpenGL->VSync?
It's very important that vsync is enabled when using non-buggy graphic
drivers.
If not, all available CPU and GPU will be used for graphics.




> If it's slow to mark a range with the keyboard shortcuts, perhaps we need
> better keyboard shortcuts for navigating...
>
> having only one key to select areas (win+b) it's a bit awkward, because if
> you want to select another area, you have first to unselect the previous
> one (win+z). The way renoise deals with this is by having two keys, one for
> range start and another one for range end. like this, you dont need to
> unselect your previous range.
>
But win+b tries to be intelligent. If you mark before the range starts, the
current range is extended, and the same is true if you mark after the range
ends.
I don't understand why it's nice to have separate keys for range start and
range end.



> To delete, use shift + right mouse button. See the "Help" menu.
>
> thanks for the tip.
> using the mouse plus the keyboard to do one action that could be done with
> just the mouse doesnt make much sense. as you said double clicking is still
> free/not used by any option.
>

Oh. I think it's far simpler to use keyboard and single mouse click
than to double click with the mouse, but perhaps if the mouse is very
good double clicking could be just as quick as using the keyboard.

Also, for most things you can right click and select "delete",
and for notes, you can just press the delete key on the keyboard.




> I don't think double clicking is used anywhere in the program except for
> opening a plugin gui.
>
> Im sorry again. sleep made me say this. i meant just one click.
> rephrasing: sometimes, when i click on the note row, instead of adding a
> note, a little hand will apear. this only happens sometimes.
>

Hand? Do you mean that the mouse pointer is transformed into a hand?



> Yes, you can edit the bin/keybindings.conf
>
> this is great to know :) i've checked the file. it wont be easy though.
> but my real questions was : can i set how many lines the keys "page up"
> and "page down" jumps in the pattern. in renoise, fastracker 2 it jumps 16
> lines (one bar).
>
>
You can scroll 16 lines if you change "32" into "16" in these two lines in
bin/keybindings.conf:

PAGE_DOWN   : ra.cursorDown 32
PAGE_UP     : ra.cursorUp 32

**Comment by Lykdraft** [comment]
> But win+b tries to be intelligent. If you mark before the range starts, the
current range is extended, and the same is true if you mark after the range
ends.
I don't understand why it's nice to have separate keys for range start and
range end.

Way, **way**  better than two. But this is what I have thought. Radium is working different but looks the same and uses from time to time even the same terminology like Renoise for example.
So until people actually **see** how (and especially how fast) stuff can be done here it's difficult to discuss these things.

**Comment by hcv242** [comment]
>Perhaps you have disabled vsync under Edit->Preferences->OpenGL->VSync?

yes, it was disabled. ive enabled it. it didnt get any faster.

>Hand? Do you mean that the mouse pointer is transformed into a hand?

yes, that's it. ive tried to make a video showing it, but the hand doesnt appear in videos or print screens.
i have found a way to make it work. if i scroll down with the cursor a few lines, it starts working ok.

>You can scroll 16 lines if you change "32" into "16" in these two lines in
bin/keybindings.conf:
PAGE_DOWN   : ra.cursorDown 32
PAGE_UP     : ra.cursorUp 32

thanks a lot for this. can i change the shortcut keys with this file ?

**Comment by kmatheussen** [comment]
On Wed, Nov 16, 2016 at 10:18 PM, hcv242 <notifications@github.com> wrote:

> Perhaps you have disabled vsync under Edit->Preferences->OpenGL->VSync?
>
> yes, it was disabled. ive enabled it. it didnt get any faster.
>

Did you restart Radium afterwards? Nothing happens until after you restart.



> Hand? Do you mean that the mouse pointer is transformed into a hand?
>
> yes, that's it. ive tried to make a video showing it, but the hand doesnt
> appear in videos or print screens.
> i have found a way to make it work. if i scroll down with the cursor a few
> lines, it starts working ok.
>

Yeah, I've seen it too. It's annoying. Needs to be fixed. It happens
now and then after  the sequencer was added a few weeks ago.



> You can scroll 16 lines if you change "32" into "16" in these two lines in
> bin/keybindings.conf:
> PAGE_DOWN : ra.cursorDown 32
> PAGE_UP : ra.cursorUp 32
>
> thanks a lot for this. can i change the shortcut keys with this file ?
>
Yes. :-)

**Comment by hcv242** [comment]
>For now, if you can't get your head around sublines/subline swing,
(see an exampleof that technique here: https://vimeo.com/162647680 )
I would highly suggest looking into PIZ Midi Tools, where you also have a midiSwing module

thanks for the tips. i know how to make swing with note delays and all that stuff, but it isnt pratical. 10 years ago i was using psycle, a tracker with no global swing, so i asked piz to make that midi swing delay. it never worked ok with psycle. dunno if it works ok with other sequencers.

**Comment by hcv242** [comment]
> Did you restart Radium afterwards? Nothing happens until after you restart.

yes i did. i always restart apps after messings with the configurations ;)

**Comment by Lykdraft** [comment]
> thanks for the tips. i know how to make swing with note delays and all that stuff, but it isnt pratical. 10 years ago i was using psycle, a tracker with no global swing, so i asked piz to make that midi swing plug. it never worked ok with psycle. dunno if it works ok with other sequencers.


Using midi swing modules **a lot** myself inside Radium. Actually on actual releases. 
Works fine in Radium, no problems at all...

Subline swing has nothing to do with Note delays or tempo changes... Way simpler... 
But hard to explain. I came up with that idea on my own... :)
But then again, global swing is already FR'd.

**Comment by kmatheussen** [comment]
On Wed, Nov 16, 2016 at 10:25 PM, hcv242 <notifications@github.com> wrote:

> Did you restart Radium afterwards? Nothing happens until after you restart.
>
> yes i did. i always restart apps after messings with the configurations ;)
>

Enabling vsync should normally make an enormous difference.
Maybe you have configured the nvidia driver to disable vsync globally?

**Comment by hcv242** [comment]
>Maybe you have configured the nvidia driver to disable vsync globally?

i've checked the driver. it was enabled globally.

**Comment by kmatheussen** [comment]
Can you try to use intel again? There should be a difference
now that vsync is enabled.

**Comment by hcv242** [comment]
just did. it's still very slow. if it's faster it's barely noticeable.

**Comment by kmatheussen** [comment]
If there are things left in this issue, please move them to new separate issues.
